
package asiap_sport;

import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;

public class booking_lapangan1 extends javax.swing.JFrame {
    double nama,harga,jmlhjual,total;

    Model_booking penjualan = new Model_booking();

//membuat code lapangan
    private void reset(){
        kode.setSelectedItem(null);
        durasi.setSelectedItem(null);
        Jam1.setSelectedItem(null);
                Jam2.setSelectedItem(null);
        txtNama1.setText(null);
        txtTeam.setText(null);
        txtNo.setText(null);
        jharga.setText(null);
        hasill.setText(null);
        sewa.setText(null);
    }
    public booking_lapangan1() {
        initComponents();
        tblBarang.setModel(penjualan.getTabel());
        
        kode.addItem("FUTSAL Rumput 01");
        kode.addItem("FUTSAL Rumput 02");
        kode.addItem("FUTSAL Matras 01");
        kode.addItem("FUTSAL Matras 02");
 
        Jam1.addItem("07.00");
        Jam1.addItem("08.00");
        Jam1.addItem("09.00");
        Jam1.addItem("10.00");
        Jam1.addItem("11.00");
        Jam1.addItem("12.00");
        Jam1.addItem("13.00");
        Jam1.addItem("14.00");
        Jam1.addItem("15.00");
        Jam1.addItem("16.00");
        Jam1.addItem("17.00");
        Jam1.addItem("18.00");
        Jam1.addItem("19.00");
        Jam1.addItem("20.00");
        Jam1.addItem("21.00");

        
        Jam2.addItem("08.00");
        Jam2.addItem("09.00");
        Jam2.addItem("10.00");
        Jam2.addItem("11.00");
        Jam2.addItem("12.00");
        Jam2.addItem("13.00");
        Jam2.addItem("14.00");
        Jam2.addItem("15.00");
        Jam2.addItem("16.00");
        Jam2.addItem("17.00");
        Jam2.addItem("18.00");
        Jam2.addItem("19.00");
        Jam2.addItem("20.00");
        Jam2.addItem("21.00");
        Jam2.addItem("22.00");

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Date = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lapangan = new javax.swing.JLabel();
        nama_pm = new javax.swing.JLabel();
        sewa = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        no_hp = new javax.swing.JLabel();
        txtTeam = new javax.swing.JTextField();
        nama_tm = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        waktu = new javax.swing.JLabel();
        jharga = new javax.swing.JTextField();
        Jam1 = new javax.swing.JComboBox();
        Jam2 = new javax.swing.JComboBox();
        kode = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        no_hp1 = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();
        hasill = new javax.swing.JTextField();
        no_hp2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lapangan1 = new javax.swing.JLabel();
        txtNama1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        miniz = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        paket = new javax.swing.JTextField();
        durasi = new javax.swing.JComboBox();
        lapangan2 = new javax.swing.JLabel();
        reset = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EldRentS");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lapangan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lapangan.setForeground(new java.awt.Color(255, 255, 255));
        lapangan.setText("Durasi");
        jPanel1.add(lapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        nama_pm.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nama_pm.setForeground(new java.awt.Color(255, 255, 255));
        nama_pm.setText("Nama Pemesan");
        jPanel1.add(nama_pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 23));

        sewa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaActionPerformed(evt);
            }
        });
        sewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sewaKeyPressed(evt);
            }
        });
        jPanel1.add(sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 227, 30));

        btnHapus.setBackground(java.awt.Color.cyan);
        btnHapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edittrash.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        no_hp.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        no_hp.setForeground(new java.awt.Color(255, 255, 255));
        no_hp.setText("Belum Terbayar");
        jPanel1.add(no_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 250, 30));

        txtTeam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeamActionPerformed(evt);
            }
        });
        txtTeam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTeamKeyPressed(evt);
            }
        });
        jPanel1.add(txtTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 227, 25));

        nama_tm.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nama_tm.setForeground(new java.awt.Color(255, 255, 255));
        nama_tm.setText("Nama Team");
        jPanel1.add(nama_tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, -1));

        txtNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoActionPerformed(evt);
            }
        });
        txtNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoKeyPressed(evt);
            }
        });
        jPanel1.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 227, 25));

        waktu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        waktu.setText("Waktu Pemesanan");
        jPanel1.add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 167, 230, -1));

        jharga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhargaActionPerformed(evt);
            }
        });
        jPanel1.add(jharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 150, 30));

        Jam1.setBackground(new java.awt.Color(51, 255, 255));
        Jam1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mulai" }));
        jPanel1.add(Jam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        Jam2.setBackground(new java.awt.Color(51, 255, 255));
        Jam2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selesai" }));
        jPanel1.add(Jam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        kode.setBackground(new java.awt.Color(51, 255, 255));
        kode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Lapangan" }));
        kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeActionPerformed(evt);
            }
        });
        jPanel1.add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 242, -1));

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblBarang);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 890, 100));

        no_hp1.setFont(new java.awt.Font("Cooper Std Black", 1, 18)); // NOI18N
        no_hp1.setForeground(new java.awt.Color(255, 255, 255));
        no_hp1.setText("Uang Muka");
        jPanel1.add(no_hp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 30));

        btnPesan.setBackground(java.awt.Color.cyan);
        btnPesan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnPesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/EDIT2.png"))); // NOI18N
        btnPesan.setText("Pesan");
        btnPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesanMouseClicked(evt);
            }
        });
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 90, -1));

        hasill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(hasill, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 150, 30));

        no_hp2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        no_hp2.setForeground(new java.awt.Color(255, 255, 255));
        no_hp2.setText("No Handphone");
        jPanel1.add(no_hp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/16 Pixel/002-folder-1.png"))); // NOI18N
        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 80, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/break.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 20, 20));

        lapangan1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lapangan1.setForeground(new java.awt.Color(255, 255, 255));
        lapangan1.setText("Lapangan");
        jPanel1.add(lapangan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 105, -1, -1));

        txtNama1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNama1ActionPerformed(evt);
            }
        });
        txtNama1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNama1KeyPressed(evt);
            }
        });
        jPanel1.add(txtNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 227, 25));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booking Lapangan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        judul.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        judul.setForeground(java.awt.Color.white);
        judul.setText("Assiap Sport");
        jPanel2.add(judul);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 940, 70));

        miniz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/downarrow2.png"))); // NOI18N
        miniz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minizMousePressed(evt);
            }
        });
        jPanel1.add(miniz, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Paket lapangan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 130, 30));

        paket.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel1.add(paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 280, 30));

        durasi.setBackground(new java.awt.Color(51, 255, 255));
        durasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", " " }));
        durasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durasiActionPerformed(evt);
            }
        });
        jPanel1.add(durasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 40, -1));

        lapangan2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lapangan2.setForeground(new java.awt.Color(255, 255, 255));
        lapangan2.setText("Harga");
        jPanel1.add(lapangan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 940, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        String[] data = new String[8];
        int[] data1 = new int[2];
        //SimpleDateFormat dformat = new SimpleDateFormat("DD MMMM YYYY");
        data[0] = (""+kode.getSelectedItem());
        data[1]= (""+durasi.getSelectedItem());
        data[2] = (""+Jam1.getSelectedItem()+"-"+Jam2.getSelectedItem());
        data[3] = txtNama1.getText();
        data[4] = txtTeam.getText();
        data[5] = txtNo.getText();
         data1[0] = Integer.parseInt(jharga.getText());
                //int a = null;
                data1[1] = Integer.parseInt(sewa.getText());
        int hasil =(data1[1] - data1[0]);
        hasill.setText(""+hasil);
        data[6] = hasill.getText();
        data[7] = sewa.getText();
        
       

        
   
        penjualan.getTabel().addRow(data);
       
    }//GEN-LAST:event_btnPesanActionPerformed

    private void sewaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sewaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sewaKeyPressed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        penjualan.getTabel().removeRow(tblBarang.getSelectedRow());
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtTeamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeamKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeamKeyPressed

    private void txtNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoKeyPressed

    private void txtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoActionPerformed

    private void sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sewaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_HORIZ);
    }//GEN-LAST:event_formWindowOpened

    private void jhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhargaActionPerformed

    private void minizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minizMousePressed
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_minizMousePressed

    private void btnPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesanMouseClicked
        //alarm a = new alarm();
        //a.setVisible(true);
    }//GEN-LAST:event_btnPesanMouseClicked

    private void txtTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeamActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Menu_Asiap_Sport a = new Menu_Asiap_Sport();
        a.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeActionPerformed
        // TODO add your handling code here:
         if(kode.getSelectedItem()=="FUTSAL Rumput 01"){
            paket.setText (" 3 buah makanan ringan + 2 buah minuman kaleng");
            
        }else if (kode.getSelectedItem()=="FUTSAL Rumput 02"){
            paket.setText (" 2 buah makanan ringan + 3 buah minuman kaleng");
            
        }else if (kode.getSelectedItem()=="FUTSAL Matras 01"){
            paket.setText (" 3 buah makanan ringan + 2 buah minuman kaleng");
        }else if (kode.getSelectedItem()=="FUTSAL Matras 02"){
            paket.setText (" 2 buah makanan ringan + 3 buah minuman kaleng");

        }
    }//GEN-LAST:event_kodeActionPerformed

    private void txtNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama1ActionPerformed

    private void txtNama1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNama1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama1KeyPressed

    private void durasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durasiActionPerformed
        // TODO add your handling code here:
        
        
        if(durasi.getSelectedItem()=="1"){
            sewa.setText("50000");
            
        }else if (durasi.getSelectedItem()=="2"){
            sewa.setText("100000");
            
        }else if (durasi.getSelectedItem()=="3"){
            sewa.setText("150000");
        }else if (durasi.getSelectedItem()=="4"){
            sewa.setText("200000");

        }
    }//GEN-LAST:event_durasiActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
reset();      // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking_lapangan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking_lapangan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking_lapangan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking_lapangan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new booking_lapangan1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JComboBox Jam1;
    private javax.swing.JComboBox Jam2;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPesan;
    private javax.swing.JComboBox durasi;
    private javax.swing.JTextField hasill;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jharga;
    private javax.swing.JLabel judul;
    private javax.swing.JComboBox kode;
    private javax.swing.JLabel lapangan;
    private javax.swing.JLabel lapangan1;
    private javax.swing.JLabel lapangan2;
    private javax.swing.JLabel miniz;
    private javax.swing.JLabel nama_pm;
    private javax.swing.JLabel nama_tm;
    private javax.swing.JLabel no_hp;
    private javax.swing.JLabel no_hp1;
    private javax.swing.JLabel no_hp2;
    private javax.swing.JTextField paket;
    private javax.swing.JToggleButton reset;
    private javax.swing.JTextField sewa;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtNama1;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtTeam;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
